//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayTide.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DayTideEntities2 : DbContext
    {
        public DayTideEntities2()
            : base("name=DayTideEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admins { get; set; }
        public DbSet<Application> Applications { get; set; }
        public DbSet<Cart> Carts { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Delevary_Man_Rating> Delevary_Man_Rating { get; set; }
        public DbSet<DeleveryMan> DeleveryMen { get; set; }
        public DbSet<Moderator> Moderators { get; set; }
        public DbSet<Notice> Notices { get; set; }
        public DbSet<Order_Detail> Order_Detail { get; set; }
        public DbSet<OrderRequest> OrderRequests { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Product_Rating> Product_Rating { get; set; }
        public DbSet<TrackProfit> TrackProfits { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
