//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayTide.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DayTideEntities1 : DbContext
    {
        public DayTideEntities1()
            : base("name=DayTideEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Delevary_Man_Rating> Delevary_Man_Rating { get; set; }
        public virtual DbSet<DeleveryMan> DeleveryMen { get; set; }
        public virtual DbSet<Moderator> Moderators { get; set; }
        public virtual DbSet<Notice> Notices { get; set; }
        public virtual DbSet<Order_Detail> Order_Detail { get; set; }
        public virtual DbSet<OrderRequest> OrderRequests { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Product_Rating> Product_Rating { get; set; }
        public virtual DbSet<TrackProfit> TrackProfits { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
