//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayTide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delevary_Man_Rating
    {
        public int Id { get; set; }
        public string DelManID { get; set; }
        public int Rating { get; set; }
        public string Comments { get; set; }
        public string CustomerId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual DeleveryMan DeleveryMan { get; set; }
    }
}
