//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayTide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderRequest
    {
        public int OrderId { get; set; }
        public string Date { get; set; }
        public string Address { get; set; }
        public string District { get; set; }
        public double Amount { get; set; }
        public string Payment_Type { get; set; }
        public string CustomerId { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
