//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayTide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackProfit
    {
        public int ProductId { get; set; }
        public int SelledQuantity { get; set; }
        public double Per_unitPrice { get; set; }
        public double Total_Price { get; set; }
        public double Profit { get; set; }
    }
}
