//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayTide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Applications = new HashSet<Application>();
            this.Notices = new HashSet<Notice>();
        }
    
        public string UserId { get; set; }
        public string Password { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual ICollection<Application> Applications { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual DeleveryMan DeleveryMan { get; set; }
        public virtual Moderator Moderator { get; set; }
        public virtual ICollection<Notice> Notices { get; set; }
    }
}
